DROP SCHEMA IF EXISTS HFW_ONETOONE_BI;

CREATE SCHEMA HFW_ONETOONE_BI;

CREATE TABLE HFW_ONETOONE_BI.PHONE (
    ID BIGINT AUTO_INCREMENT,
    NUMBER VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE HFW_ONETOONE_BI.PHONEDETAILS (
    ID BIGINT AUTO_INCREMENT,
    PROVIDER VARCHAR(255),
    TECHNOLOGY VARCHAR(255),
    PHONE_ID BIGINT,
    PRIMARY KEY (ID)
);

ALTER TABLE HFW_ONETOONE_BI.PHONEDETAILS
ADD CONSTRAINT HFW_ONETOONE_BI_PHONEDETAILS_FK 
FOREIGN KEY (PHONE_ID) REFERENCES HFW_ONETOONE_BI.PHONE(ID);