CREATE SEQUENCE ROLL_NUMBER_TABLE_SEQ;
CREATE TABLE ID_GENERATOR(sequence_name VARCHAR, NEXT_VAL BIGINT); 
insert into ID_GENERATOR values('ROLL_NUMBER_TABLE_SEQ', 0);
ALTER SEQUENCE ROLL_NUMBER_TABLE_SEQ RESTART WITH 1;
DROP TABLE IF EXISTS HFW_STUDENT_TABLE;

CREATE TABLE HFW_STUDENT_TABLE
	(ROLL_NUMBER			BIGINT PRIMARY KEY,
	 NAME 					VARCHAR(50) NOT NULL,
	 EMAIL					VARCHAR(50),
	 MOBILE					VARCHAR(10),
	 ADDRESS				VARCHAR(200));