CREATE SEQUENCE ROLL_NUMBER_SEQ;
ALTER SEQUENCE ROLL_NUMBER_SEQ RESTART WITH 1;
DROP TABLE IF EXISTS HFW_STUDENT_SEQUENCE;

CREATE TABLE HFW_STUDENT_SEQUENCE
	(ROLL_NUMBER			BIGINT PRIMARY KEY,
	 NAME 					VARCHAR(50) NOT NULL,
	 EMAIL					VARCHAR(50),
	 MOBILE					VARCHAR(10),
	 ADDRESS				VARCHAR(200));