DROP SEQUENCE IF EXISTS HIBERNATE_SEQUENCE;
CREATE SEQUENCE HIBERNATE_SEQUENCE;
ALTER SEQUENCE HIBERNATE_SEQUENCE RESTART WITH 1001;

DROP TABLE IF EXISTS HFW_STUDENT_AUTO;
CREATE TABLE HFW_STUDENT_AUTO
	(ROLL_NUMBER			BIGINT PRIMARY KEY,
	 NAME 					VARCHAR(50) NOT NULL,
	 EMAIL					VARCHAR(50),
	 MOBILE					VARCHAR(10),
	 ADDRESS				VARCHAR(200));