DROP SCHEMA IF EXISTS HFW_MANYTOONE;

CREATE SCHEMA HFW_MANYTOONE;

CREATE TABLE HFW_MANYTOONE.Person (
    id BIGINT AUTO_INCREMENT,
    PRIMARY KEY (id)
);

CREATE TABLE HFW_MANYTOONE.Phone (
    id BIGINT AUTO_INCREMENT,
    number VARCHAR(255),
    person_id BIGINT,
    PRIMARY KEY (id)
 );

ALTER TABLE HFW_MANYTOONE.Phone
ADD CONSTRAINT HFW_MANYTOONE_PERSON_ID_FK
FOREIGN KEY (person_id) REFERENCES HFW_MANYTOONE.Person;