DROP SCHEMA IF EXISTS HFW_ONETOONE_UNI;

CREATE SCHEMA HFW_ONETOONE_UNI;

CREATE TABLE HFW_ONETOONE_UNI.PHONE (
    ID BIGINT AUTO_INCREMENT,
    NUMBER VARCHAR(255),
    DETAILS_ID BIGINT,
    PRIMARY KEY ( ID )
);

CREATE TABLE HFW_ONETOONE_UNI.PHONEDETAILS (
    ID BIGINT AUTO_INCREMENT,
    PROVIDER VARCHAR(255),
    TECHNOLOGY VARCHAR(255),
    PRIMARY KEY ( ID )
);

ALTER TABLE HFW_ONETOONE_UNI.PHONE
ADD CONSTRAINT HFW_ONETOONE_UNI_PHONE_FK 
FOREIGN KEY (DETAILS_ID) REFERENCES HFW_ONETOONE_UNI.PHONEDETAILS(ID);