CREATE TABLE HFW_ONETOMANY_TRAINER 
  ( 
     ID                BIGINT AUTO_INCREMENT, 
     NAME              VARCHAR(50), 
     MOBILE_NUMBER     VARCHAR(10), 
     TRAINER_DETAIL_ID BIGINT, 
     PRIMARY KEY(ID), 
     FOREIGN KEY (TRAINER_DETAIL_ID) REFERENCES HFW_ONETOONE_TRAINER_DETAIL (ID) 
  );
  
  
CREATE TABLE HFW_ONETOMANY_COURSE 
  ( 
     ID      BIGINT AUTO_INCREMENT, 
     TITLE   VARCHAR(50), 
     TRAINER_ID BIGINT,
     
     PRIMARY KEY(ID),
     UNIQUE KEY TITLE_UNIQUE_KEY (TITLE),
     FOREIGN KEY (TRAINER_ID) REFERENCES HFW_ONETOMANY_TRAINER(ID)
  );