ALTER USER sa SET PASSWORD '';

CREATE SEQUENCE ROLL_NUMBER_SEQ;

ALTER SEQUENCE ROLL_NUMBER_SEQ RESTART WITH 1;

DROP TABLE IF EXISTS HFW_STUDENT;

CREATE TABLE HFW_STUDENT
	(ROLL_NUMBER			BIGINT PRIMARY KEY,
	 NAME 					VARCHAR(50) NOT NULL,
	 EMAIL					VARCHAR(50),
	 MOBILE					VARCHAR(10),
	 ADDRESS				VARCHAR(200));
	 
INSERT INTO HFW_STUDENT VALUES(1000, 'Atul Dwivedi', 'contact@atuldwivedi.com', '9110460027', 'Bengaluru');